os: osx
osx_image: xcode14
language: swift
script: xcodebuild clean build test -project EssentialFeed.xcodeproj -scheme "CI" -sdk iphonesimulator16.0 -destination "platform=iOS Simulator,name=iPhone12,OS=16.0" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

